model:
  base_learning_rate: 4.5e-06
  target: ldm.models.autoencoder.VQModel
  params:
    embed_dim: 4
    n_embed: 16384
    monitor: val/rec_loss
    ddconfig:
      double_z: false
      z_channels: 4
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions: [32]
      dropout: 0.0
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_num_layers: 2
        disc_start: 1
        disc_weight: 0.6
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 24
    train:
      target: taming.data.annotated_objects_coco.AnnotatedObjectsCoco
      params:
        data_path: ../datasets/coco/2017  # substitute with path to full dataset
        split: train
        keys: [image, objects_bbox, file_name, annotations]
        no_tokens: 1024
        target_image_size: 256
        min_object_area: 0.00001
        min_objects_per_image: 2
        max_objects_per_image: 30
        crop_method: random-1d
        random_flip: true
        use_group_parameter: true
        encode_crop: true
    validation:
      target: taming.data.annotated_objects_coco.AnnotatedObjectsCoco
      params:
        data_path: ../datasets/coco/2017  # substitute with path to full dataset
        split: validation
        keys: [image, objects_bbox, file_name, annotations]
        no_tokens: 1024
        target_image_size: 256
        min_object_area: 0.00001
        min_objects_per_image: 2
        max_objects_per_image: 30
        crop_method: center
        random_flip: false
        use_group_parameter: true
        encode_crop: true
    test:
      target: taming.data.annotated_objects_coco.AnnotatedObjectsCoco
      params:
        data_path: ../datasets/coco/2017  # substitute with path to full dataset
        split: validation
        keys: [image, objects_bbox, file_name, annotations]
        no_tokens: 1024
        target_image_size: 256
        min_object_area: 0.0000001
        min_objects_per_image: 2
        max_objects_per_image: 30
        crop_method: center
        random_flip: false
        use_group_parameter: true
        encode_crop: true

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 99
        increase_log_steps: False

lightning:
  trainer:
    max_epochs: 50
